language: ruby
rvm:
  - 2.0.0
gemfile:
  - Gemfile
services: mongodb
before_script:
  - gem install bundler
script:
  - cp -f config/travis.mongoid.yml config/mongoid.yml 
  - bundle exec rspec -c
notifications:
  emails:
    - guitarpopno.t330@gmail.com
  on_success: always # default: change
  on_failure: always
