development:
  sessions:
    default:
      database: <%= ENV['MONGOHQ_DB_URL'].split('/').last %>
      username: <%= ENV['MONGOHQ_DB_URL'].split(':')[1].split("/").last %>
      password: <%= ENV['MONGOHQ_DB_URL'].split(':')[2].split('@').first %>
      hosts:
        - dharma.mongohq.com:10082
      options:
  options:
test:
  sessions:
    default:
      database: actress_app_test
      hosts:
        - localhost:27017
      options:
production:
  sessions:
    default:
      database: <%= ENV['MONGOHQ_DB_URL'].split('/').last %>
      username: <%= ENV['MONGOHQ_DB_URL'].split(':')[1].split("/").last %>
      password: <%= ENV['MONGOHQ_DB_URL'].split(':')[2].split('@').first %>
      hosts:
        - dharma.mongohq.com:10082
      options:
  options:
    use_utc: false
    use_activesupport_time_zone: true
